### PR TITLE
allow parameters to be send

### PR DESCRIPTION
**Pull request by shabanovd**
Base on [documentation](https://feathersjs.com/api/services.html) `create`, `get`, `update`, `patch` and `remove` service methods have `params` argument.

```
async get(id: Id, params: Params) {}
async create(data: any, params: Params) {}
async update(id: NullableId, data: any, params: Params) {}
async patch(id: NullableId, data: any, params: Params) {}
async remove(id: NullableId, params: Params) {}
```

This PR is adding `params` argument to all that methods.

### CODE REVIEW

**Comment by Dahkenangnon** [comment]
Hi @shabanovd 

Any description about your PR please ?

What the new feature feature do you enable ?

Then I can review and merge.

Thank, for starting to contribute to this.... waiting for  your reply

**Comment by shabanovd** [comment]
Hey @Dahkenangnon, I updated the description. Let me know if you still have questions.

**Comment by Dahkenangnon** [comment]
> Base on [documentation](https://feathersjs.com/api/services.html) `create`, `get`, `update`, `patch` and `remove` service methods have `params` argument.
> 
> ```
> async get(id: Id, params: Params) {}
> async create(data: any, params: Params) {}
> async update(id: NullableId, data: any, params: Params) {}
> async patch(id: NullableId, data: any, params: Params) {}
> async remove(id: NullableId, params: Params) {}
> ```
> 
> This PR is adding `params` argument to all that methods.

These `params` argument are new feature enabled by recent version of the featherjs framwork. Even I merged be sure to have the right version on your backend.

**Comment by shabanovd** [comment]
It's quite old staff, see https://buzzard.docs.feathersjs.com/api/services.html

**Comment by Dahkenangnon** [comment]
> https://buzzard.docs.feathersjs.com/api/services.html

Nice dear

**Comment by Dahkenangnon** [comment]
> It's quite old staff, see https://buzzard.docs.feathersjs.com/api/services.html

Are you interested to become core contributor for this packages ?

**Comment by Dahkenangnon** [comment]
> > It's quite old staff, see https://buzzard.docs.feathersjs.com/api/services.html
> 
> Are you interested to become core contributor for this packages ?

@shabanovd , I need some help to keep maintaining it. We can continue discussion  via email if you want

**Comment by shabanovd** [comment]
@Dahkenangnon sure, I can help you with it.

**Pull request merged**
